// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BulkGenerationController from "./bulk_generation_controller"
application.register("bulk-generation", BulkGenerationController)

import ChoicesSelectController from "./choices_select_controller"
application.register("choices-select", ChoicesSelectController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import KeywordFilterController from "./keyword_filter_controller"
application.register("keyword-filter", KeywordFilterController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ModalOpenerController from "./modal_opener_controller"
application.register("modal-opener", ModalOpenerController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PlatformSelectorController from "./platform_selector_controller"
application.register("platform-selector", PlatformSelectorController)

import PublishFormController from "./publish_form_controller"
application.register("publish-form", PublishFormController)
